name: hive_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # For UI template
  velocity_x: ^0.3.2

  # Random Color Generator
  random_color: ^1.0.5

  # Highlighted package
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  # For defining database storage location
  path_provider: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # For generating TypeAdapter
  hive_generator: ^0.7.0+2

  # For code generation
  build_runner: ^1.10.0

dependency_overrides:
  quiver: 2.1.0

flutter:
  uses-material-design: true
